### ISSUE TITLE
Biomes Development

### ISSUE THREAD

**Issue by CEKlopfenstein** [CEKlopfenstein/p5.js-Random-2D-Height-Map#12]
### Overview
The plan for biomes is to make it so that the color of the cells is not just determined by the height but by other variables as well. This is to improve the detail of the map in a way. Even if it's a small improvement.
### ToDo List
- [ ] Modify Cell Object to hold biome data
- [ ] Determine how biome will be determined
- [ ] Save biome data to a file
- [ ] Load biome data from a file

**Comment by CEKlopfenstein** [comment]
### Biome Table
As of 5/3/2020 4:43 pm EST
| Integer value | Biome | Conditions |
|:---:|:---|:---|
| 0 | Deep Ocean | Height equal to or below 85 |
| 1 | Shallow Ocean | Height equal to or below 127 but greater than 85 |
| 2 | Beach | Is neighboring an ocean or has a neighbor next to an ocean |
| 3 | Grass Land  | Anything above 127 that is not a beach |

**Comment by CEKlopfenstein** [comment]
![image](https://user-images.githubusercontent.com/49758590/82768204-83189580-9dfb-11ea-82af-cfd581c1a3cc.png)
[This is the results of this commit.](https://github.com/CEKlopfenstein/p5.js-Random-2D-Height-Map/commit/0790b744c601d3e91fa34ce4bd2f3b74062d8171)
